# Site settings
title: Platform Engineering
email: help@platformengineering.team
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: platformengineeringnz

collections_dir: collections
collections:
  casestudies:
    output: true
  principles:
    output: false
  services:
    output: false
  team:
    output: false
  technologies:
    output: false

excerpt_separator: <!--more-->
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3
